-- MySQL Script generated by MySQL Workbench
-- Mon May 18 11:36:21 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `POS` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `POS` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `POS` ;

-- -----------------------------------------------------
-- Table `auditorias_stocks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `auditorias_stocks` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `auditorias_stocks` (
  `id_auditoria_stock` INT NOT NULL AUTO_INCREMENT,
  `tipo_movimiento` ENUM('ingreso', 'venta', 'traslado') NOT NULL,
  `cantidad` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `fk_variante_producto` INT NOT NULL,
  `fk_usuario` INT NOT NULL,
  `fk_deposito_origen` INT NULL,
  `fk_deposito_destino` INT NULL,
  PRIMARY KEY (`id_auditoria_stock`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_auditoria_stock_UNIQUE` ON `auditorias_stocks` (`id_auditoria_stock` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `categorias` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `categorias` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nombre_categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_categoria_UNIQUE` ON `categorias` (`id_categoria` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clientes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `clientes` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nombre_cliente` VARCHAR(45) NOT NULL,
  `apellido_cliente` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `tipo` ENUM('minorista', 'mayorista') NOT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_cliente_UNIQUE` ON `clientes` (`id_cliente` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `depositos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `depositos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `depositos` (
  `id_deposito` INT NOT NULL AUTO_INCREMENT,
  `lugar_deposito` ENUM('local', 'almacen') NOT NULL,
  PRIMARY KEY (`id_deposito`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_deposito_UNIQUE` ON `depositos` (`id_deposito` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `descuentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `descuentos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `descuentos` (
  `id_descuento` INT NOT NULL AUTO_INCREMENT,
  `nombre_descuento` VARCHAR(45) NOT NULL,
  `porcentaje_descuento` DOUBLE NOT NULL,
  PRIMARY KEY (`id_descuento`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_descuento_UNIQUE` ON `descuentos` (`id_descuento` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `detalles_ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `detalles_ventas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `detalles_ventas` (
  `id_detalle_venta` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL,
  `fk_venta` INT NOT NULL,
  `fk_variante_producto` INT NOT NULL,
  PRIMARY KEY (`id_detalle_venta`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_detalle_venta_UNIQUE` ON `detalles_ventas` (`id_detalle_venta` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `envios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `envios` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `envios` (
  `id_envio` INT NOT NULL AUTO_INCREMENT,
  `numero_seguimiento` VARCHAR(45) NOT NULL,
  `estado` ENUM('pendiente', 'despachado', 'entregado') NOT NULL,
  `fecha_despacho` DATE NULL,
  `fk_venta` INT NOT NULL,
  PRIMARY KEY (`id_envio`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_envio_UNIQUE` ON `envios` (`id_envio` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `metodos_de_pagos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `metodos_de_pagos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `metodos_de_pagos` (
  `id_metodo_de_pago` INT NOT NULL AUTO_INCREMENT,
  `tipo` ENUM('efectivo', 'transferencia', 'debito') NOT NULL,
  PRIMARY KEY (`id_metodo_de_pago`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_metodo_de_pago_UNIQUE` ON `metodos_de_pagos` (`id_metodo_de_pago` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `productos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `productos` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre_producto` VARCHAR(45) NOT NULL,
  `descripcion_producto` VARCHAR(45) NOT NULL,
  `fk_categoria` INT NOT NULL,
  `fk_proveedor` INT NOT NULL,
  PRIMARY KEY (`id_producto`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_productos_UNIQUE` ON `productos` (`id_producto` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `proveedores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proveedores` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `proveedores` (
  `id_proveedor` INT NOT NULL AUTO_INCREMENT,
  `nombreEmpresa` VARCHAR(45) NOT NULL,
  `nombreContacto` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_proveedor`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_proveedor_UNIQUE` ON `proveedores` (`id_proveedor` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `stocks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stocks` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `stocks` (
  `id_stock` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL,
  `fk_deposito` INT NOT NULL,
  `fk_variante_producto` INT NOT NULL,
  PRIMARY KEY (`id_stock`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_stock_UNIQUE` ON `stocks` (`id_stock` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuarios` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(45) NOT NULL,
  `apellido_usuario` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `contrasenia` VARCHAR(255) NOT NULL,
  `rol` ENUM('admin', 'cajero', 'repositor') NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_usuario_UNIQUE` ON `usuarios` (`id_usuario` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `variantes_productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `variantes_productos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `variantes_productos` (
  `id_variante_producto` INT NOT NULL AUTO_INCREMENT,
  `talle` VARCHAR(45) NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `precio_venta` DOUBLE NOT NULL,
  `fk_producto` INT NOT NULL,
  PRIMARY KEY (`id_variante_producto`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_variante_producto_UNIQUE` ON `variantes_productos` (`id_variante_producto` ASC) ;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ventas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ventas` (
  `id_venta` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `total_neto` DOUBLE NOT NULL,
  `total_bruto` DOUBLE NOT NULL,
  `fk_usuario` INT NOT NULL,
  `fk_cliente` INT NOT NULL,
  `fk_metodo_de_pago` INT NOT NULL,
  `fk_descuento` INT NULL,
  PRIMARY KEY (`id_venta`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_venta_UNIQUE` ON `ventas` (`id_venta` ASC) ;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
